version: '3.7'
services:
 minecraft:
   image: itzg/minecraft-server
   ports:
     - "25565:25565"
   environment:
     EULA: "TRUE"
   deploy:
     resources:
       requests:
         cpus: 1
         memory: 2
   volumes:
     - "minecraft:/data"